### ISSUE TITLE
When I try running `example_03_flower_depth.py` it 

### ISSUE THREAD

**Issue by Shade5** [cicwi/plenoptomos#1]
When I try running `example_03_flower_depth.py` it crashes with 
```
proj_id = astra.create_projector('cuda3d', self.proj_geom, vg, opts)
TypeError: create_projector() takes 3 positional arguments but 4 were given
```

**Comment by Obi-Wan** [comment]
Hi, which version of the ASTRA toolbox are you using?
I suggest you to update ASTRA to a more recent version (anything released within the last two and a half years :) ).

The fix was pushed upstream to ASTRA in this commit: https://github.com/astra-toolbox/astra-toolbox/commit/ee0118aceff644f7e5cdb0c7298c41064357d86a

**Comment by Shade5** [comment]
Yup installing the latest version of astra-toolbox from source fixed it! Thanks

**Comment by Shade5** [comment]
There's still this issue when I try the example;
`TypeError: compute_depth_map() got an unexpected keyword argument 'lambda_smooth'`

**Comment by Shade5** [comment]
Just made this change:
```
-dm = pleno.depth.compute_depth_map(dc, lambda_tv=1.0, lambda_smooth=None)
+dm = pleno.depth.compute_depth_map(dc, lambda_tv=1.0, lambda_d2=None)
```
